#!/usr/bin/env python3
"""Render distribution LaTeX as native MathML for the interactive explorer.

The source is _data/interview_distribution_formulas.yml. Use the same MathML
converter as the lesson equations, then commit the generated JavaScript.

    python3 scripts/render_distribution_math.py
    python3 scripts/render_distribution_math.py --check
"""

import argparse
import json
from pathlib import Path

import yaml

from render_math import mathml


ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "_data" / "interview_distribution_formulas.yml"
OUTPUT = ROOT / "js" / "components" / "interview-distribution-math.js"


def build():
    data = yaml.safe_load(SOURCE.read_text())
    if not isinstance(data, dict) or not data:
        raise ValueError("Expected a nonempty formula mapping")
    rendered = {}
    for name, pair in data.items():
        if set(pair) != {"density", "cdf"}:
            raise ValueError(f"{name} must define density and cdf")
        rendered[name] = {}
        for kind, tex in pair.items():
            markup = mathml(tex, display=True)
            if "\\" in markup:
                raise ValueError(f"{name} {kind} has an unrendered LaTeX command")
            rendered[name][kind] = markup
    return (
        "/* GENERATED by scripts/render_distribution_math.py. Do not hand-edit. */\n"
        "(function () {\n"
        "  var formulas = " + json.dumps(rendered, ensure_ascii=False, sort_keys=True,
                                        separators=(",", ":")) + ";\n"
        "  if (typeof module !== 'undefined' && module.exports) module.exports = formulas;\n"
        "  else window.INTERVIEW_DISTRIBUTION_FORMULAS = formulas;\n"
        "}());\n"
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = build()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != generated:
            print(f"Stale generated formulas in {OUTPUT}")
            return 1
        print("Distribution MathML is current")
    else:
        OUTPUT.write_text(generated)
        print(f"Wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
