#!/usr/bin/env python3
"""
Solve every 2x2 game on /game-theory/ and write _data/game_theory.yml.

The equilibria on that page are computed here, not typed by hand. Getting
Chicken or Stag Hunt wrong from memory is easy, and a wrong equilibrium is a
wrong claim about how a real situation resolves.

For each game this finds:
  * pure Nash equilibria, by checking that neither player gains by deviating
  * the mixed Nash equilibrium, where one exists in the interior
  * strictly dominant strategies
  * Pareto-efficient outcomes
  * whether the game is zero-sum

Payoffs are (row, column). Run after editing games.json:

    python3 scripts/solve_games.py            # rewrites _data/game_theory.yml
    python3 scripts/solve_games.py --check    # verifies without writing
"""
import argparse
import json
import os
import sys
from fractions import Fraction

ROW, COL = 0, 1
CELLS = [('a', 0, 0), ('b', 0, 1), ('c', 1, 0), ('d', 1, 1)]


def payoff(g, i, j, who):
    return Fraction(g['payoffs'][i][j][who])


def pure_equilibria(g):
    """A cell is Nash when neither player improves by switching alone."""
    out = []
    for i in (0, 1):
        for j in (0, 1):
            row_ok = payoff(g, i, j, ROW) >= payoff(g, 1 - i, j, ROW)
            col_ok = payoff(g, i, j, COL) >= payoff(g, i, 1 - j, COL)
            if row_ok and col_ok:
                out.append([i, j])
    return out


def dominant(g, who):
    """A strictly dominant strategy beats the alternative against every reply."""
    for s in (0, 1):
        if who == ROW:
            better = all(payoff(g, s, j, ROW) > payoff(g, 1 - s, j, ROW) for j in (0, 1))
        else:
            better = all(payoff(g, i, s, COL) > payoff(g, i, 1 - s, COL) for i in (0, 1))
        if better:
            return s
    return None


def mixed_equilibrium(g):
    """
    Interior mixed equilibrium for 2x2.

    Row mixes so the column player is indifferent, and vice versa. Returns the
    probability each player puts on their first strategy, or None when no
    interior solution exists.
    """
    # column player indifferent between its two strategies
    # p * C(0,0) + (1-p) * C(1,0) == p * C(0,1) + (1-p) * C(1,1)
    num_p = payoff(g, 1, 1, COL) - payoff(g, 1, 0, COL)
    den_p = (payoff(g, 0, 0, COL) - payoff(g, 0, 1, COL)) - (payoff(g, 1, 0, COL) - payoff(g, 1, 1, COL))
    num_q = payoff(g, 1, 1, ROW) - payoff(g, 0, 1, ROW)
    den_q = (payoff(g, 0, 0, ROW) - payoff(g, 1, 0, ROW)) - (payoff(g, 0, 1, ROW) - payoff(g, 1, 1, ROW))
    if den_p == 0 or den_q == 0:
        return None
    p = num_p / den_p
    q = num_q / den_q
    if not (0 < p < 1 and 0 < q < 1):
        return None
    return {'row': [float(p), float(1 - p)], 'col': [float(q), float(1 - q)]}


def pareto(g):
    """Cells where no other cell is at least as good for both and better for one."""
    pts = [((i, j), (payoff(g, i, j, ROW), payoff(g, i, j, COL))) for i in (0, 1) for j in (0, 1)]
    out = []
    for cell, (r, c) in pts:
        dominated = any(r2 >= r and c2 >= c and (r2 > r or c2 > c) for _, (r2, c2) in pts)
        if not dominated:
            out.append([cell[0], cell[1]])
    return out


def zero_sum(g):
    total = {payoff(g, i, j, ROW) + payoff(g, i, j, COL) for i in (0, 1) for j in (0, 1)}
    return len(total) == 1


def solve(g):
    return {
        'pure': pure_equilibria(g),
        'mixed': mixed_equilibrium(g),
        'dominant_row': dominant(g, ROW),
        'dominant_col': dominant(g, COL),
        'pareto': pareto(g),
        'zero_sum': zero_sum(g),
    }


def esc(s):
    return '"' + str(s).replace('\\', '\\\\').replace('"', '\\"') + '"'


def emit(src):
    games, laws, levers = src['games'], src['laws'], src['levers']
    dashboard, classifier = src['dashboard'], src['classifier']
    L = [
        '# Game theory — /game-theory/',
        '# Consumed by _pages/game-theory.md and js/components/game-theory.js.',
        '#',
        '# The `solved:` block on each game is GENERATED by scripts/solve_games.py.',
        '# Do not hand-edit it. Change `payoffs` and re-run the script instead, so',
        '# the stated equilibria always follow from the numbers actually shown.',
        '#',
        '# payoffs[row][col] = [row player payoff, column player payoff]',
        '',
        'games:',
    ]
    for g in games:
        s = g['solved']
        L.append(f"  - id: {g['id']}")
        L.append(f"    name: {esc(g['name'])}")
        L.append(f"    life: {esc(g['life'])}")
        L.append(f"    icon: {g['icon']}")
        L.append(f"    rows: [{esc(g['rows'][0])}, {esc(g['rows'][1])}]")
        L.append(f"    cols: [{esc(g['cols'][0])}, {esc(g['cols'][1])}]")
        L.append(f"    payoffs: {json.dumps(g['payoffs'])}")
        L.append(f"    reading: {esc(g['reading'])}")
        L.append(f"    move: {esc(g['move'])}")
        L.append('    solved:')
        L.append(f"      pure: {json.dumps(s['pure'])}")
        L.append(f"      mixed: {json.dumps(s['mixed'])}")
        L.append(f"      dominant_row: {json.dumps(s['dominant_row'])}")
        L.append(f"      dominant_col: {json.dumps(s['dominant_col'])}")
        L.append(f"      pareto: {json.dumps(s['pareto'])}")
        L.append(f"      zero_sum: {json.dumps(s['zero_sum'])}")
        L.append('')

    L.append('levers:')
    for x in levers:
        L.append(f"  - key: {esc(x['key'])}")
        L.append(f"    icon: {x['icon']}")
        L.append(f"    ask: {esc(x['ask'])}")
        L.append(f"    example: {esc(x['example'])}")
        L.append('')

    L.append('laws:')
    for i, x in enumerate(laws, 1):
        L.append(f"  - n: {i}")
        L.append(f"    icon: {x['icon']}")
        L.append(f"    law: {esc(x['law'])}")
        L.append(f"    why: {esc(x['why'])}")
        L.append('')

    L.append('dashboard:')
    for x in dashboard:
        L.append(f"  - key: {esc(x['key'])}")
        L.append(f"    icon: {x['icon']}")
        L.append(f"    ask: {esc(x['ask'])}")
        L.append(f"    floor: {json.dumps(x['floor'])}")
        L.append('')

    L.append('classifier:')
    for x in classifier:
        L.append(f"  - q: {esc(x['q'])}")
        L.append(f"    icon: {x['icon']}")
        L.append(f"    why: {esc(x['why'])}")
        L.append('')

    L.append('five:')
    for x in src['five']:
        L.append(f"  - key: {esc(x['key'])}")
        L.append(f"    icon: {x['icon']}")
        L.append(f"    vs: {esc(x['vs'])}")
        L.append(f"    ask: {esc(x['ask'])}")
        L.append(f"    note: {esc(x['note'])}")
        L.append('')

    L.append('domains:')
    for x in src['domains']:
        L.append(f"  - key: {esc(x['key'])}")
        L.append(f"    icon: {x['icon']}")
        L.append(f"    group: {x['group']}")
        L.append(f"    games: [{', '.join(esc(g) for g in x['games'])}]")
        L.append(f"    winning: {esc(x['winning'])}")
        L.append(f"    risk: {esc(x['risk'])}")
        L.append(f"    ask: {esc(x['ask'])}")
        L.append(f"    math: {esc(x['math']) if x.get('math') else '\"\"'}")
        L.append('')

    L.append('regimes:')
    for x in src['regimes']:
        L.append(f"  - key: {esc(x['key'])}")
        L.append(f"    icon: {x['icon']}")
        L.append(f"    when: {esc(x['when'])}")
        L.append(f"    opt: {esc(x['opt'])}")
        L.append(f"    avoid: {esc(x['avoid'])}")
        L.append('')

    L.append('readiness:')
    for x in src['readiness']:
        L.append(f"  - q: {x['q']}")
        L.append(f"    icon: {x['icon']}")
        L.append(f"    t: {esc(x['t'])}")
        L.append(f"    body: {esc(x['body'])}")
        L.append(f"    rule: {esc(x['rule'])}")
        L.append('')
    return '\n'.join(L)



def main():
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.dirname(here)
    ap = argparse.ArgumentParser()
    ap.add_argument('--src', default=os.path.join(here, 'games.json'))
    ap.add_argument('--out', default=os.path.join(root, '_data', 'game_theory.yml'))
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args()

    src = json.load(open(args.src))
    for g in src['games']:
        g['solved'] = solve(g)

    print(f"{'game':22s} {'pure NE':18s} {'mixed':8s} {'dom':6s} zero-sum")
    for g in src['games']:
        s = g['solved']
        cells = ','.join(dict(zip('01', '')) .get(str(i), '') or f"({g['rows'][i]},{g['cols'][j]})"
                         for i, j in s['pure']) or 'none'
        dom = ''.join(['R' if s['dominant_row'] is not None else '-',
                       'C' if s['dominant_col'] is not None else '-'])
        print(f"{g['id']:22s} {cells[:18]:18s} {'yes' if s['mixed'] else 'no':8s} {dom:6s} {s['zero_sum']}")

    text = emit(src)
    if args.check:
        if not os.path.exists(args.out):
            print('\nno data file to check against')
            return 1
        same = open(args.out).read() == text
        print('\n' + ('data file matches the solver' if same
                      else 'DATA FILE IS STALE, re-run without --check'))
        return 0 if same else 1
    open(args.out, 'w').write(text)
    print(f'\nwrote {args.out} ({len(src["games"])} games)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
